baseURL = "https://cives.cfd"
title = "Spectral"
languageCode = "es-es"
defaultContentLanguage = "en"
paginate = "7"
theme = "spectral"

[params]
fancyTitle = "Cives" # title for frontpage, may include image
copyright = "Cives, ac"
description = 'Justicia pronta. <br /> Cives, Centro de Arbitraje.'
startbuttonText = "Artículos."
startbuttonLink = "/posts/"
body_is_markdown = true
#custom_css = "foo.css"
#images = ["path_to_social_image_for_link_previews.jpg"]

[[params.menu.main]]
url = '/'
title = "Home"

[[params.menu.main]]
url = '/posts/'
title = "Posts"

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"
    
# No entiendo esto de los parametros si la taxonomia no coincide

[params.one]
enable = true
title = 'Cada año el número de causas judiciales crece<br />y la de las sentencias decrecen'
body = '''
Aunque parece ser un mal mundial en nuestro país es notable la desproporción entre la calidad de acceso a la Justicia y el crecimiendo de su [calidad](/posts/calidad/)
'''

#Arriba se escapa del toml con ''' fijate que no se pone content en el link!!

[[params.one.icon]]
icon = "fa-diamond"
style = "1"
label = "Lorem"

[[params.one.icon]]
icon = "fa-heart-o"
style = "2"
label = "Ipsum"

[[params.one.icon]]
icon = "fa-code"
style = "3"
label = "Dolor"

# Otra clase de parámentros.  

[params.two]
enable = true

[[params.two.section]]
img = "img/pic01.jpg"
title = 'El arbitraje es el instrumento perfecto para estabilizar los negocios'
body = 'No cuesta nada, si no hay conflicto. Si lo hay, ambas partes se ven extensamente beneficiadas.'

[[params.two.section]]
img = "img/pic02.jpg"
title = 'Las partes se aseguran una pronta resolución'
body = 'Un juicio en primera instancia tarda cuanto menos dos años en resolverse. Si ambas partes litigan como es debido, la causa no se resolverá jamás.'

[[params.two.section]]
img = "img/pic03.jpg"
title = 'La demanda crece, la calidad decrece'
body = 'El Poder Judicial hace cuanto puede con los recursos que le son asignados.'

# Otra sección. 

[params.three]
enable = true
title = 'Accumsan mus tortor nunc aliquet'
body = '''
Aliquam ut ex ut augue consectetur interdum. Donec amet imperdiet eleifend  
fringilla tincidunt. Nullam dui leo Aenean mi ligula, rhoncus ullamcorper.
'''

[[params.three.feature]]
icon = "fa-paper-plane-o"
title = "Arcu accumsan"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "fa-laptop"
title = "Ac Augue Eget"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "fa-code"
title = "Foo bar"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "fa-headphones"
title = "Baz kram"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "fa-heart-o"
title = "Some latin text"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "fa-flag-o"
title = "Nothing important"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[params.cta]
enable = true
title = "Arcue ut vel commodo"
body = "Aliquam ut ex ut augue consectetur interdum endrerit imperdiet amet eleifend fringilla."

[[params.cta.link]]
href = "/reemplazar_por_link.md"
text = "Activate"
special = true

[[params.cta.link]]
href = "/reemplazar_por_link.md"
text = "Learn More"
special = false

[params.contact]
enable = true
title = "Contact"
body = "Leave us a message."
phone = "+49 (0) 030 000 000"
address = "1234 Somewhere Road<br />Some Place, Some State 0000<br />Some Country"
email = "nospam@example.com"
subject = "New Submission!"
formspree_form_id = "example_invalid"

[params.social]
twitter = ""
facebook = ""
instagram = ""
dribble = ""

# language specific options

[languages.en]
weight = 0
languageName = "English"

[languages.de]
weight = 10
languageName = "Deutsch"
